### ISSUE TITLE
Left padding too small

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#14]
-- need more padding (perhaps double?) on left edge
-- should be based on either font-size or rectangle size, not a fixed number of pixels

<img width="977" alt="image" src="https://user-images.githubusercontent.com/737638/130317568-8c5b00c5-d2ad-4448-b138-b049a8864237.png">

**Comment by Real-John-Cheung** [comment]
now padding will be 15% of the width and height of the rectangle, with the min value of 2px and the max value of 20px
> need more padding (perhaps double?) on left edge 

I think it will be a bit strange, after the padding is set according to the width of the rectangle... maybe better keep both side the same so the text is centered

**Comment by dhowe** [comment]
agreed, better keep left and right side equal
