### ISSUE TITLE
Ad rectangles with multiple colors

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#15]
What _seems_ to be happening here is that the ad initially loads, then later reloads, but only the inner text is reloaded

example: nytimes.com

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/737638/130317642-42d65ce7-c027-4d6d-a3e8-511fbc998824.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/737638/130317677-8383aedd-5083-4797-b479-8b9356bc782e.png">

**Comment by Real-John-Cheung** [comment]
this should be fixed by https://github.com/dhowe/AdLiPo/commit/bfefc2c0db1dd87b29248c7d9d25d3975851a7d5
