### ISSUE TITLE
Performance issue / warning

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#16]
https://edition.cnn.com/2021/08/20/tennis/naomi-osaka-defeat-cincinnati-spt-intl/index.html

This must never happen:

![image](https://user-images.githubusercontent.com/737638/130317786-0a48e009-9591-4884-b3e2-15767be47450.png)

**Comment by Real-John-Cheung** [comment]
Should be fixed with https://github.com/dhowe/AdLiPo/commit/2a6c1f758bb2fa51303c24bdbade3b0f220129bf
tested on Firefox and Chrome
