### ISSUE TITLE
Ad layout not ideal

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#18]
This should be a bigger font -- pls check that top/bottom padding is not too large and causing this problem:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/737638/130319120-92557e56-1820-4528-9eae-5297cf533387.png">

**Comment by Real-John-Cheung** [comment]
should be fixed in https://github.com/dhowe/AdLiPo/commit/3bb4c3d1fd4cfeb3030d97a2f82b123848040fe8 
now padding will be set according to the width and height of the rectangle
