### ISSUE TITLE
Add constraint: text width / rectangle width > X

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#19]
Add constraint so that text width / rectangle width is greater than some percent (start with 2/3)

The following ads should not be allowed:

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/737638/130319303-c7e3a2a7-0db6-4a15-a24a-37a2ef693add.png">

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/737638/130319337-d1b1d74b-25c8-4846-9644-41fa5cca52d3.png">

**Comment by Real-John-Cheung** [comment]
line length check added in https://github.com/dhowe/AdLiPo/commit/c391a158be3b24826e25f1b7818f20801e441003
