### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#32]
Why do we have /AdLiPo/AdLiPo ?

**Comment by Real-John-Cheung** [comment]
That's because we are not forking ublock here, so I put files added (files that not exist in ublock) into /AdLiPo/AdLiPo, then it might be easier for us to update ublock when we need to... 
Maybe we should change the folder name to something else ...

**Comment by dhowe** [comment]
Yes, it's a bit confusing as is. But what you say about uBlock updates is a good point -- we need to do one shortly in any case

**Comment by dhowe** [comment]
Tasks, as discussed:

- [ ] delete ublock submodule
- [ ] create a new folder called 'ublock', containing unchanged source code for ublock
- [ ] move stuff in ChangedFiles to the top level (also changed adLiPoImage to either 'img' or 'image')
- [ ] update make-firefox.sh and make-chrome.sh scripts
- [ ] verify that docs in README.md are still correct
