### ISSUE TITLE
Create dynamicLayout() function

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPo#5]
Given a width, height, and padding for a div, and a text-string, should first compute the largest font-size that will fit the text (computeFontSize function), then assign the proper CSS (doLayout function).

- [x] should correctly computes the correct font size
- [x] correctly handles different padding values (a single value for 4 edges)
- [x] avoid 'orphans' (use &nbsp; for last space)

**Assumptions**
- Can assume Bench9 (via ttf or google font)
- Can assume left horizontal alignment
- Can assume center vertical alignment
- Can use whatever word-break is easiest

<br>

**Comment by dhowe** [comment]
1. Please include screenshots of 1-2 of the worst cases of what you describe above
2. The padding argument doesn't seem to be working yet
2. Have you considered using Canvas.measureText method (see this [post](https://stackoverflow.com/a/21015393)) ? I believe this is what I did previously, and it should be more accurate and simpler

**Comment by Real-John-Cheung** [comment]
> Please include screenshots of 1-2 of the worst cases of what you describe above
Here is some cases (it is not very common)
<img width="386" alt="螢幕截圖 2021-06-03 下午9 25 46" src="https://user-images.githubusercontent.com/61215358/120652412-5721fc80-c4b2-11eb-8111-b823c93748ef.png">

<img width="535" alt="螢幕截圖 2021-06-03 下午9 23 37" src="https://user-images.githubusercontent.com/61215358/120652187-1a560580-c4b2-11eb-974f-ca5c94d8a9cb.png">

**Comment by dhowe** [comment]
These aren't too bad. I think your method is likely fine without needing the canvas.
